-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 19:32:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema diplom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diplom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diplom` DEFAULT CHARACTER SET utf8mb3 ;
USE `diplom` ;

-- -----------------------------------------------------
-- Table `diplom`.`типтс`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`типтс` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Имя` VARCHAR(250) NOT NULL,
  `Код` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Имя` ASC) VISIBLE,
  UNIQUE INDEX `Code_UNIQUE` (`Код` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`брендытс`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`брендытс` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ТипТС` INT NOT NULL,
  `Имя` VARCHAR(250) NOT NULL,
  `Код` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `BrandName_UNIQUE` (`Имя` ASC) VISIBLE,
  UNIQUE INDEX `BrandCode_UNIQUE` (`Код` ASC) VISIBLE,
  INDEX `FK_transportvehiclebrands_transportvehiclebrands_idx` (`ТипТС` ASC) VISIBLE,
  CONSTRAINT `FK_transportvehiclebrands_transportvehiclebrands`
    FOREIGN KEY (`ТипТС`)
    REFERENCES `diplom`.`типтс` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`подразделения`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`подразделения` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Имя` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `DivisionName_UNIQUE` (`Имя` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`маршруты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`маршруты` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Код` VARCHAR(50) NOT NULL,
  `Имя` VARCHAR(250) NOT NULL,
  `Длина` FLOAT NOT NULL,
  `Время_впути` FLOAT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Code_UNIQUE` (`Код` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Имя` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`организации`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`организации` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Имя` VARCHAR(250) NOT NULL,
  `Директор` VARCHAR(250) NOT NULL,
  `Индивид_налогномер` VARCHAR(10) NOT NULL,
  `Контакт_детали` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Имя` ASC) VISIBLE,
  UNIQUE INDEX `IndividualTaxNumber_UNIQUE` (`Индивид_налогномер` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`ставки`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`ставки` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Код` VARCHAR(50) NOT NULL,
  `Имя` VARCHAR(250) NOT NULL,
  `Ед_ставки` FLOAT NOT NULL,
  `Объем` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Code_UNIQUE` (`Код` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Имя` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`услуги`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`услуги` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Имя` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Имя` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`заказы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`заказы` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Маршрут` INT NOT NULL,
  `Подразделение` INT NOT NULL,
  `Покупатель` INT NOT NULL,
  `Услуги` INT NOT NULL,
  `Ставка` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_divisions_orders_idx` (`Подразделение` ASC) VISIBLE,
  INDEX `FK_orders_orders_idx` (`Маршрут` ASC) VISIBLE,
  INDEX `FK_organizations_orders_idx` (`Покупатель` ASC) VISIBLE,
  INDEX `FK_rates_orders_idx` (`Ставка` ASC) VISIBLE,
  INDEX `FK_services_orders_idx` (`Услуги` ASC) VISIBLE,
  CONSTRAINT `FK_divisions_orders`
    FOREIGN KEY (`Подразделение`)
    REFERENCES `diplom`.`подразделения` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_orders_orders`
    FOREIGN KEY (`Маршрут`)
    REFERENCES `diplom`.`маршруты` (`Id`),
  CONSTRAINT `FK_organizations_orders`
    FOREIGN KEY (`Покупатель`)
    REFERENCES `diplom`.`организации` (`Id`),
  CONSTRAINT `FK_rates_orders`
    FOREIGN KEY (`Ставка`)
    REFERENCES `diplom`.`ставки` (`Id`),
  CONSTRAINT `FK_services_orders`
    FOREIGN KEY (`Услуги`)
    REFERENCES `diplom`.`услуги` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`топливо`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`топливо` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Код` VARCHAR(50) NOT NULL,
  `Имя` VARCHAR(250) NOT NULL,
  `Плотность` FLOAT NOT NULL,
  `Ед_измер` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `FuelCode_UNIQUE` (`Код` ASC) VISIBLE,
  UNIQUE INDEX `FuelName_UNIQUE` (`Имя` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`прававодителя`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`прававодителя` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Служ_номер` VARCHAR(5) NOT NULL,
  `ФИО` VARCHAR(250) NOT NULL,
  `Класс` VARCHAR(50) NOT NULL,
  `Категория` VARCHAR(3) NOT NULL,
  `ID_карты` VARCHAR(10) NOT NULL,
  `Тариф_час` DOUBLE NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `DriverFullName_UNIQUE` (`ФИО` ASC) VISIBLE,
  UNIQUE INDEX `ServiceNumber_UNIQUE` (`Служ_номер` ASC) VISIBLE,
  UNIQUE INDEX `IdentityCardNumber_UNIQUE` (`ID_карты` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`тс`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`тс` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Гос_номер` VARCHAR(6) NOT NULL,
  `Бренд_код` INT NOT NULL,
  `Код_подразделения` INT NOT NULL,
  `Основ_топливо` INT NOT NULL,
  `Доп_топливо` INT NOT NULL,
  `Имя_подразделения` INT NOT NULL,
  `Основ_потребление` INT NOT NULL,
  `Коэф_доппотребления` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `StateNumber_UNIQUE` (`Гос_номер` ASC) VISIBLE,
  INDEX `FK_transportvehicles_additionalfuels_idx` (`Доп_топливо` ASC) VISIBLE,
  INDEX `FK_transportvehicles_brands_idx` (`Бренд_код` ASC) VISIBLE,
  INDEX `FK_transportvehicles_divisions_idx` (`Код_подразделения` ASC) VISIBLE,
  INDEX `FK_transportvehicles_drivernames_idx` (`Имя_подразделения` ASC) VISIBLE,
  INDEX `FK_transportvehicles_mainfuels_idx` (`Основ_топливо` ASC) VISIBLE,
  CONSTRAINT `FK_transportvehicles_additionalfuels`
    FOREIGN KEY (`Доп_топливо`)
    REFERENCES `diplom`.`топливо` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_transportvehicles_brands`
    FOREIGN KEY (`Бренд_код`)
    REFERENCES `diplom`.`брендытс` (`Id`),
  CONSTRAINT `FK_transportvehicles_divisions`
    FOREIGN KEY (`Код_подразделения`)
    REFERENCES `diplom`.`подразделения` (`Id`),
  CONSTRAINT `FK_transportvehicles_drivernames`
    FOREIGN KEY (`Имя_подразделения`)
    REFERENCES `diplom`.`прававодителя` (`Id`),
  CONSTRAINT `FK_transportvehicles_mainfuels`
    FOREIGN KEY (`Основ_топливо`)
    REFERENCES `diplom`.`топливо` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`накладные`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`накладные` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Дата_выпуска` DATETIME NOT NULL,
  `Дата_обработки` DATETIME NOT NULL,
  `Гос_номер` INT NOT NULL,
  `Спидометр_отправка` INT NOT NULL,
  `Спидометр_конец` INT NOT NULL,
  `Топливо_начало` INT NOT NULL,
  `Топливо_потрачено` INT NOT NULL,
  `Топливо_конец` INT NOT NULL,
  `Топливо_пропущенно` INT NOT NULL,
  `Заказ` INT NOT NULL,
  `Дата_отправки` DATETIME NOT NULL,
  `Дата_возврат` DATETIME NOT NULL,
  `Время_ремонт` FLOAT NOT NULL,
  `Время_вождения` FLOAT NOT NULL,
  `ВечернееВремя` FLOAT NOT NULL,
  `НочноеВРемя` FLOAT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_orders_waybills_idx` (`Заказ` ASC) VISIBLE,
  INDEX `FK_transportvehicles_waybills_idx` (`Гос_номер` ASC) VISIBLE,
  CONSTRAINT `FK_orders_waybills`
    FOREIGN KEY (`Заказ`)
    REFERENCES `diplom`.`заказы` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_transportvehicles_waybills`
    FOREIGN KEY (`Гос_номер`)
    REFERENCES `diplom`.`тс` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`типплатежей`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`типплатежей` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Имя` VARCHAR(50) NOT NULL,
  `Код` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Имя` ASC) VISIBLE,
  UNIQUE INDEX `Code_UNIQUE` (`Код` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diplom`.`платежи`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`платежи` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Накладная` INT NOT NULL,
  `Тип_платежа` INT NOT NULL,
  `Сумма` DOUBLE NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_payments_payments_idx` (`Тип_платежа` ASC) VISIBLE,
  INDEX `FK_waybills_payments_idx` (`Накладная` ASC) VISIBLE,
  CONSTRAINT `FK_payments_payments`
    FOREIGN KEY (`Тип_платежа`)
    REFERENCES `diplom`.`типплатежей` (`Id`),
  CONSTRAINT `FK_waybills_payments`
    FOREIGN KEY (`Накладная`)
    REFERENCES `diplom`.`накладные` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
